name: 'Changes with matrix as output in specific folder'
description: 'Construct dynamic matrix of changed services based on previous commit'
inputs:
  token:
    description: 'Github token'
    reqired: true
  folder:
    description: 'Where services are located'
    required: false
    default: '.'
  exclude:
    description: 'Which folder to exclude. Could be a comma-separated list or multiline'
    required: false
    default: ''
outputs:
  martrix:
    description: 'Output matrix for changed directories'
runs:
  using: 'node20'
  main: 'dist/index.js'
