name: 'Changes with matrix as output in specific folder'
description: 'Construct dynamic matrix of changed services based on previous commit'
inputs:
  token:
    description: 'Github token'
    reqired: true
  folder:
    description: 'Where services are located (root folder of all services inside your monorepo)'
    required: false
    default: ''
  include:
    description: 'Which folder to include, multiline input'
    required: false
    default: ''
  exclude:
    description: 'Which folder to exclude, multiline input'
    required: false
    default: ''
outputs:
  martrix:
    description: 'Output matrix for changed directories'
runs:
  using: 'node20'
  main: 'dist/index.js'
